---
- hosts: pi
  remote_user: pi
  become: yes
  vars:
    version: 3.7.0
    threads: 4
  tasks:
    - name: check if python 3.7 is installed
      shell: which python3.7
      register: python3
    - name: copy python installer
      copy:
        src: files/python3.7-installer.sh
        dest: /tmp/python3.7-installer.sh
      when: python3.stdout == ""
    - name: run python installer
      shell: ./python3.7-installer.sh
      args:
        chdir: /tmp
      when: python3.stdout == ""
    - name: install screen
      apt:
        name: screen
        state: present
    - name: install pipenv
      pip:
        name: pipenv
        state: present
