---
- hosts: pi
  remote_user: pi
  become: yes
  gather_facts: no
  tasks:
    - name: install sqlite
      apt:
        name: sqlite
        state: present
    - name: create app folder
      file:
        path: /home/pi/weather
        state: directory
        mode: 0755
        owner: pi
        group: pi
    - name: copy app
      copy:
        src: "{{ item }}"
        dest: /home/pi/weather/
        owner: pi
        group: pi
      with_items:
        - Pipfile
        - Pipfile.lock
        - station.py
        - gcp_key.json
      tags:
        - files
    - name: setup exec flags
      file:
        path: /home/pi/weather/station.py
        mode: 0755
    - name: install deps
      shell: pipenv install
      args:
        chdir: /home/pi/weather/
    - name: copy station.sh
      copy:
        src: station.sh
        dest: /etc/init.d/station.sh
        mode: 0755
    - name: setup station
      shell: update-rc.d station.sh defaults
    - name: start station
      shell: /etc/init.d/station.sh start

